import clsx from 'clsx';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import ReactQueryProvider from '@/components/providers/ReactQueryProvider';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const sfPro = localFont({
  src: [
    {
      path: '../fonts/SFPro/SF-Pro-Text-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/SFPro/SF-Pro-Text-RegularItalic.otf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../fonts/SFPro/SF-Pro-Text-Medium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../fonts/SFPro/SF-Pro-Text-Semibold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../fonts/SFPro/SF-Pro-Text-Bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-sfpro',
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={clsx(sfPro.variable, 'antialiased')}>
        <ReactQueryProvider>
          {children}
          <Toaster position='top-right' closeButton />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
